export const Theme = {
  colors: {
    tableHeaderBackgroundColor: '#004691',
    tableHeaderColor: '#004691',
    menuBackgroundColor: "#f5f5f5",
    menuBackgroundColorActive: "#D0D0D0AB",
    background: "#f5f5f5",
    textPrimary: "#212121",
    textDisabled: "#666666",
    textPrimaryDark: "#FFFFFF",
    textSecondary: "#9E9E9E",
    buttonColorPrimary: "#ffffff",
    buttonBackgroundPrimary: "#007aff",
    buttonBackgroundActive: "#0056b3",
    buttonBackgroundDisabled: "#cccccc",
    buttonBackgroundSecondary: "#FFF",
    buttonBackgroundWarning: "#ff9800",
    buttonBackgroundWarningActive: "#e68900",
    buttonBackgroundError: "#e53935",
    buttonBackgroundErrorActive: "#c62828",
    buttonBackgroundCancel: "#FFD350",
    buttonBackgroundCancelActive: "#FFBF00",
    separatorColor: "#ddd",
    cardBackground: "#ffffff",
    borderColor: "#D5D5D5",
    borderColorActiveActiveFocus: "#555555",
    icon: "#FFFFFF",
    darkIcon: "#555",
    border: "#e0e0e0",
    link: "#007aff",
    error: "#e53935",
    success: "#43a047",
  },
  fontSizes: {
    small: 14,
    medium: 16,
    large: 20,
    extraLarge: 24,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
  },
  borderRadius: {
    default: 8,
    round: 50,
  },
  shadows: {
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 24,
      elevation: 5, // Para Android
    },
    button: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 3,
    },
  },
};
