-- MySQL Script generated by MySQL Workbench
-- Mon 03 Feb 2025 09:19:02 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop-flow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop-flow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop-flow` ;
USE `shop-flow` ;

-- -----------------------------------------------------
-- Table `shop-flow`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `stock` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `category_id` INT NOT NULL,
  `image_url` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shop-flow`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`cart_item` (
  `created_at` DATETIME NOT NULL,
  `users_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  INDEX `fk_cart_item_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_cart_item_product1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`, `product_id`),
  CONSTRAINT `fk_cart_item_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `shop-flow`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop-flow`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`order_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total_price` VARCHAR(45) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT NOT NULL,
  `order_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_order_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shop-flow`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `shop-flow`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`ordem_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`ordem_item` (
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL NOT NULL,
  `total_price` DECIMAL NOT NULL,
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`quantity`, `product_id`, `order_id`),
  INDEX `fk_ordem_item_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_ordem_item_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop-flow`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `shop-flow`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop-flow`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop-flow`.`user_roles` (
  `users_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `fk_user_roles_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_user_roles_role1_idx` (`role_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`, `role_id`),
  CONSTRAINT `fk_user_roles_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `shop-flow`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `shop-flow`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
