version: '3.9'

services:
  mysql-dev:
    image: mysql:8.0 
    container_name: mysql-shopflow-dev
    restart: unless-stopped  # Reinicia automaticamente em caso de falha ou reinício do Docker
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: shop-flow        
      MYSQL_USER: dev               
      MYSQL_PASSWORD: dev       
    ports:
      - "3306:3306" 
