export const theme = {
  colors: {
    menuBackgroundColor: "#FFF",
    menuBackgroundColorHover: "#D0D0D0AB",
    background: "#f5f5f5",
    textPrimary: "#212121",
    textPrimaryDark: "#FFFFFF",
    textSecondary: "#757575",
    buttonColorPrimary: "#ffffff",
    buttonBackgroundPrimary: "#007aff",
    buttonBackgroundHover: "#0056b3",
    buttonBackgroundSecondary: "#ff6f61",
    cardBackground: "#ffffff",
    borderColor: "#D5D5D5",
    borderColorHoverActiveFocus: "#555555",
    icon: "#FFFFFF",
    darkIcon: "#555",
    border: "#e0e0e0",
    link: "#007aff",
    error: "#e53935",
    success: "#43a047",
  },
  fontSizes: {
    small: "0.875rem",
    medium: "1rem",
    large: "1.25rem",
    extraLarge: "1.5rem",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.7rem",
    md: "1.05rem",
    lg: "1.7rem",
  },
  borderRadius: {
    default: "8px",
    round: "50%",
  },
  shadows: {
    card: "0 4px 6px rgba(0, 0, 0, 0.1)",
    button: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
};
